### ISSUE TITLE
Schedule is off by 1 hour

### ISSUE THREAD

**Issue by cmaumet** [ohbm/hackathon2020#101]
I think the schedule we have in: https://ohbm.github.io/hackathon2020/schedule/ is currently off by 1 hour compared to what we have planned for the hubs. The times displayed correspond to Beijing/Denver/Paris timezone (not Bankgok/LA/London as indicated).

Shall we change the times (alternative is changing the cities)

**Comment by Remi-Gau** [comment]
We need to cross check that with #110

**Comment by Remi-Gau** [comment]
@cmaumet forgot to check that one.

**Comment by cmaumet** [comment]
I think this is still off by 1 hour compared to [our hub schematic](https://docs.google.com/spreadsheets/d/1IwMFfrNV8nuF8m3rLVspwtAVzqcLU6FybkAtp28Lhfk/edit#gid=1670357951): e.g. Beijing intro is at 9am on the sheet and 10am on the website.
