### ISSUE TITLE
Add hub labels on the hackathon page

### ISSUE THREAD

**Issue by Remi-Gau** [ohbm/hackathon2020#168]
- possibly sort the projects by hub

**Comment by DorienHuijser** [comment]
I could just add a new line in the project description for now?
`  details: "Hub: EMEA 
<br>PROJECT DESCRIPTION.
<br>*description* 
<br>More info..." `
?

**Comment by Remi-Gau** [comment]
actually something that will give us more flexibility: 
add a new `hub` key to the template of the `projects.yml` file like this:

```
# -
#   title: "Your awesome project"
#   # images must be put in the img/hackathon folder. If there is no image you can use whatever.png
#   image: whatever.png
#   details: "PROJECT DESCRIPTION.<br>Tell us about what you want to achieve. More information here: <a href=https://github.com/ohbm/hackathon2020/issues/INSERT_ISSUE_NUMBER_HERE</a>"
#   hub: Asia-Pacific / Europe-Middle east-Africa / Americas
```

And add it to all the projects we have already: this way can reinject the content of that key however we want when the Jekyll generate the html pages.

Makes sense?

**Comment by DorienHuijser** [comment]
Yes, will include this in my next update!

**Comment by Remi-Gau** [comment]
You are star. Thanks. :pray:
