### ISSUE TITLE
Schedule page for HackTrack & TrainTrack

### ISSUE THREAD

**Issue by llevitis** [ohbm/hackathon2020#19]
- [x] Add columns for TrainTrack & HackTrack 
- [x] Replicate schedule from 2018 or 2019 for now

**Comment by Remi-Gau** [comment]
Did you have any ideas in mind for the schedule page? 

As a beginning (for the site launch) should we have what the "general schedule" will look like and a link to the google sheet with how everything is split in each time zone?
