### ISSUE TITLE
General

### ISSUE THREAD

**Issue by Remi-Gau** [ohbm/hackathon2020#21]
- [x] change logo that appears in browser tab, navbar and footer
- [x] twitter handle
- [x] hashtag
- [x] add a dedicated image to each page
- [x] change the banner "unconference talk" banner that appears when scrolling down
- [x] create labels for the different projects types in issues
- [x] create a project issue template
- [x] use images from https://undraw.co/illustrations
- [x] registration and helper sign up spreadsheet

**Comment by sofievdbos** [comment]
- [ ] logo is not well visible when displayed on a "busy" banner (e.g. Schedule and Hackathon)
