### ISSUE TITLE
Team

### ISSUE THREAD

**Issue by Remi-Gau** [ohbm/hackathon2020#22]
- [x] update the about us
- [x] debug layout: Organizers: name and role are not fully displayed if they take three lines or more
- [x] add brainhack global team
- [x] add teams from each hub

**Comment by sofievdbos** [comment]
- [ ] debug layout: 
_Organizers_: name and role are not fully displayed if they take three lines or more

**Comment by llevitis** [comment]
working on the "about us" fix here: https://github.com/llevitis/hackathon2020/tree/2020_04_21_update_to_virtual_event
