### ISSUE TITLE
Distributed page

### ISSUE THREAD

**Issue by sofievdbos** [ohbm/hackathon2020#30]

**Comment by Remi-Gau** [comment]
@sofievdbos you are working on this, right?

**Comment by sofievdbos** [comment]
@Remi-Gau That was the idea; but I haven't created the online page yet; just adapted the Google Drive document. Should I start creating the page; or should I wait on an update wrt to the new format due to COVID-19?

**Comment by Remi-Gau** [comment]
Yes it makes sense to wait. I was just trying to assign certain tasks to certain people. :-)

**Comment by sofievdbos** [comment]
Then feel free to assign this to me; and we will see how we can proceed when we have some more clarity. :-)
