### ISSUE TITLE
website can't be loaded in China

### ISSUE THREAD

**Issue by Remi-Gau** [ohbm/hackathon2020#41]
from mattermost chat:

>After checking both the hackathon website and the OS-SIG website are not accessible from China... 
For the hackathon website, I'm hoping we can make it work as it's based on github pages (and those are not 'banned' from China). 
Can you think of  any specific tool/service you are currently using (in addition to Github pages) that could be the root cause of that inaccessibility?

>Just got an email: the issue is probably related to the use of "google-fonts and related service" 

![Image Pasted at 2020-4-30 13-49](https://user-images.githubusercontent.com/6961185/80742594-ede7f100-8b1b-11ea-92b6-29edff50b1d6.png)

**Comment by Remi-Gau** [comment]
Seems that trying to fix this messed up  the display of the our "roles" on the team card: 

They are supposed to look like that but do not in the master branch anymore.

![team_details](https://user-images.githubusercontent.com/6961185/81018592-244ba600-8e65-11ea-9645-72da411ef132.png)

**Comment by cmaumet** [comment]
I think this looks good on my end (i.e. hovering does display the role). Can we close this issue or am I missing something here? Thanks!

**Comment by Remi-Gau** [comment]
Yes this is fixed. Some small issues are still bugging my inner OCD but he (because it has to be a dude) is not back from the hike I sent him on. So We will live with it.
