### ISSUE TITLE
Add contributors

### ISSUE THREAD

**Issue by Remi-Gau** [ohbm/hackathon2020#93]
Will use the all contributors bot to add contributors to the readme file.

This might open a large number of PR so don't panic.

**Comment by Remi-Gau** [comment]
@all-contributors please add @llevitis for code content doc design eventOrganizing ideas infra maintenance review projectManagement

**Comment by Remi-Gau** [comment]
@all-contributors please add @cmaumet  for code content doc design eventOrganizing ideas infra maintenance review projectManagement

**Comment by Remi-Gau** [comment]
@all-contributors please add @Remi-Gau  for code content doc design eventOrganizing ideas infra maintenance review projectManagement

**Comment by Remi-Gau** [comment]
@all-contributors please add @complexbrains for content doc ideas review

**Comment by Remi-Gau** [comment]
@all-contributors please add @gkiar for code design

**Comment by Remi-Gau** [comment]
@all-contributors please add @sofievdbos  for content doc ideas review

**Comment by Remi-Gau** [comment]
@all-contributors please add @jhlegarreta  for content doc ideas review

**Comment by Remi-Gau** [comment]
hey @DorienHuijser 
I will let you use the all contributors bot to add yourself automatically to the website contributor on the README.

Pasting the following message in an issue should do it. Scroll above to see how it works. :-)

```
@all-contributors please add @DorienHuijser for code infra maintenance review
```

**Comment by DorienHuijser** [comment]
@all-contributors please add @DorienHuijser for code infra maintenance review

**Comment by Remi-Gau** [comment]
@all-contributors please add @anibalsolon for code doc design ideas maintenance

**Comment by Remi-Gau** [comment]
@all-contributors please add @crohr for code design maintenance

**Comment by Remi-Gau** [comment]
@all-contributors please add @malvikasharan for infra ideas

**Comment by llevitis** [comment]
@all-contributors please add @robertoostenveld for code doc

**Comment by Remi-Gau** [comment]
closing old issues of mine
